// packages/next/components/PostHeader.tsx
import tw from "~/styles/tw.module.css";
import dayjs from "dayjs";

const PostHeader = (post: any) => {
  const author = JSON.parse(process.env.author!);
  const m = post.date ? dayjs(post.date) : null;
  const dateString = m ? m.format("ddd D MMMM YYYY") : "";

  return (
    <section className="mb-4">
      <a
        className="el-author"
        href={author.url}
        target="_blank"
        rel="noreferrer noopener nofollow"
      >
        <span className="image">
          <img className="is-rounded" src={author.image} alt={author.name} />
        </span>
        <span>{author.name}</span>
      </a>

      <div className={tw["flex-grow"]} />

      <div>{dateString}</div>

      <style jsx>{`
        section:first-child {
          display: flex;
          flex-direction: row;
          white-space: nowrap;
          overflow: auto;
        }

        .el-author {
          display: flex;
          flex-direction: row;
          white-space: nowrap;
          justify-content: center;
        }

        .el-author img {
          border: none;
          display: block;
          width: 24px;
          min-width: 24px;
        }

        .el-author span + span {
          margin-left: 0.5rem;
        }
      `}</style>
    </section>
  );
};

export default PostHeader;

// packages/nuxt/components/PostHeader.vue
<template>
  <section class="PostHeader">
    <a
      class="el-author"
      :href="author.url"
      target="_blank"
      rel="noreferrer noopener nofollow"
    >
      <span class="image">
        <img class="is-rounded" :src="authorImage" :alt="author.name" />
      </span>
      <span>{{ author.name }}</span>
    </a>

    <div class="flex-row">
      <div class="spacer" />
      <div>{{ post.date | formatDate }}</div>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'
import { THEME } from '~/assets/global'

@Component
export default class PostHeader extends Vue {
  @Prop({ required: true }) post!: any

  author = THEME.author

  get authorImage() {
    return this.author.image
  }
}
</script>

<style lang="scss" scoped>
.PostHeader {
  display: flex;
  flex-direction: row;

  > * {
    margin-bottom: 0.5rem;
  }

  .flex-row {
    display: flex;
    flex-direction: row;
    flex-grow: 1;

    .spacer {
      flex-grow: 1;
    }
  }

  @media (max-width: 501px) {
    flex-direction: column-reverse;

    .flex-row {
      margin-top: -1rem;
    }
  }
}

.el-author {
  display: flex;
  flex-direction: row;
  white-space: nowrap;
  align-items: center;

  img {
    border: none;
    display: block;
    width: 24px;
    min-width: 24px;
  }

  span + span {
    margin-left: 0.5rem;
  }
}
</style>
