// pages/.vitepress/theme/Layout.vue
<template>
  <section>
    <nav class="navbar has-shadow is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a href="/" class="navbar-item">
          <h1 style="font-weight: 700">{{ banner }}</h1>
        </a>

        <div :class="$style['flex-grow']" />

        <PageSocial v-if="$mq === 'tablet'" />

        <a role="button" class="navbar-burger burger" :class="{ 'is-active': isNavExpanded }" aria-label="menu"
          :aria-expanded="isNavExpanded" tabIndex="0" data-target="navbarMain" @click="isNavExpanded = !isNavExpanded"
          @keypress="isNavExpanded = !isNavExpanded">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarMain" class="navbar-menu" :class="{ 'is-active': isNavExpanded }">
        <div class="navbar-start">
          <a v-for="t in tabs" :key="t.href || t.id" class="navbar-item" :href="t.href || ('/tab/' + t.id)"
            :target="t.href ? '_blank' : ''" :rel="t.href ? 'noopener nofollow noreferrer' : undefined">
            {{ t.name }}
          </a>
        </div>

        <div class="navbar-end">
          <PageSocial v-if="$mq !== 'tablet'" class="mobile:w-full" />

          <form class="field has-addons m-2 px-2" @submit.prevent="$router.push(`/blog?q=${q}`)">
            <div class="control is-expanded" role="search">
              <input v-model="q" class="input" type="search" placeholder="Search" aria-label="search" />
            </div>

            <div class="control">
              <button class="button" style="
                  border-top-right-radius: 100%;
                  border-bottom-right-radius: 100%;
                ">
                <span class="icon">
                  <FontAwesome icon="search" />
                </span>
              </button>
            </div>
          </form>
        </div>
      </div>
    </nav>

    <article style="margin-top: 60px">
      <div class="container">
        <div class="columns">
          <main class="column mt-4 is-6-desktop is-offset-1-desktop">
            <Content />
          </main>

          <aside class="column is-4">
            <section class="card mt-4">
              <header class="card-header">
                <h3 class="card-header-title">Tag Cloud</h3>
              </header>

              <article class="card-content">
                <span v-for="t in computedTags" :key="t.name" class="el-tag mr-2">
                  <a :href="`/tag/${t.name}`" :class="t.class">{{
                      t.name
                  }}</a>
                </span>
              </article>
            </section>

            <section class="card mt-4">
              <a ref="twitter" class="twitter-timeline" data-height="800" :href="`https://twitter.com/patarapolw`">
                {{ `Tweets by patarapolw` }}
              </a>
            </section>
          </aside>
        </div>
      </div>
    </article>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vitepress'

const banner = "polv's coding blog"
const tabs: {
  name: string
  id: string
  q: string
}[] = [
    {
      "name": "Pinned",
      "id": "pinned",
      "q": "category:pinned"
    },
    {
      "name": "Health",
      "id": "health",
      "q": "tag:health"
    },
    {
      "name": "Windows",
      "id": "windows",
      "q": "category:windows"
    },
    {
      "name": "macOS",
      "id": "macos",
      "q": "category:macos"
    },
    {
      "name": "Linux",
      "id": "linux",
      "q": "category:linux"
    },
    {
      "name": "Cross-platform",
      "id": "crossplatform",
      "q": "tag:crossplatform"
    }
  ]

const tagCloudData = JSON.parse('{}') // TODO: load from file
const excluded = new Set<string>([])
const computedTags: {
  name: string
  class: string
}[] = Object.keys(tagCloudData)
  .sort((a, b) => {
    const primary = tagCloudData[b] - tagCloudData[a]
    if (primary) {
      return primary
    }
    return a.localeCompare(b)
  })
  .slice(0, 30)
  .map((t) => {
    if (excluded.has(t)) {
      return null
    }
    return {
      name: t,
      class: (() => {
        const count = tagCloudData[t]
        // if (count > 20) {
        //   return 'c20'
        // } else
        // if (count > 10) {
        //   return 'c10'
        // } else
        if (count > 5) {
          return 'c5'
        } else if (count > 3) {
          return 'c3'
        } else if (count > 1) {
          return 'c2'
        }
        return 'c1'
      })(),
    }
  })
  .map((el) => el!)
  .filter((el) => el)

const q = ref('')
const isNavExpanded = ref(false)

const router = useRouter()

function onSearch() {
  router.go(`/search?q=${encodeURIComponent(q.value)}`)
}

onMounted(() => {
  document.body.append(Object.assign(document.createElement('script'), {
    src: 'https://platform.twitter.com/widgets.js',
    charSet: 'utf-8',
    async: true
  }))
})
</script>

<style module scoped src="./tw.module.css">
</style>

<style scoped>
.c20 {
  font-size: 6rem;
}

.c10 {
  font-size: 3rem;
}

.c5 {
  font-size: 1.8rem;
}

.c3 {
  font-size: 1.2rem;
}

.c2 {
  font-size: 0.9rem;
}

.c1 {
  font-size: 0.6rem;
}

@media screen and (max-width: 600px) {
  .mobile\:w-full {
    width: 100%;
  }
}

.el-tag {
  white-space: nowrap;
}

aside article {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
}
</style>

// packages/next/components/Layout.tsx
import { faSearch } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { THEME } from '~/assets/global'
import tw from '~/styles/tw.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { ReactNode, createRef, useEffect, useState } from 'react'

const Layout = ({
  tagCount,
  children
}: {
  tagCount: Record<string, number>
  children: ReactNode | ReactNode[]
}) => {
  const router = useRouter()

  const [isTablet, setTablet] = useState(false)
  const [isNavExpanded, setNavExpanded] = useState(false)
  const [q, setQ] = useState(router.query.q as string)

  const twitterRef = createRef<HTMLAnchorElement>()

  const computedTags = Object.keys(tagCount)
    .sort((a, b) => {
      const primary = tagCount[b] - tagCount[a]
      if (primary) {
        return primary
      }
      return a.localeCompare(b)
    })
    .slice(0, 30)
    .map((t) => {
      return {
        name: t,
        class: (() => {
          const count = tagCount[t]
          // if (count > 20) {
          //   return 'c20'
          // } else
          // if (count > 10) {
          //   return 'c10'
          // } else
          if (count > 5) {
            return 'c5'
          } else if (count > 3) {
            return 'c3'
          } else if (count > 1) {
            return 'c2'
          }
          return 'c1'
        })()
      }
    })
    .filter((el) => el)

  useEffect(() => {
    setTablet(matchMedia('(max-width: 600px)').matches)
  }, [0])

  return (
    <section>
      <nav
        className="navbar has-shadow is-fixed-top"
        role="navigation"
        aria-label="main navigation"
      >
        <div className="navbar-brand">
          <Link href="/">
            <a className="navbar-item">
              <h1 style={{ fontWeight: 700 }}>{THEME.banner}</h1>
            </a>
          </Link>

          <div className={tw['flex-grow']}></div>

          {THEME.social && isTablet ? <PageSocial /> : null}

          <a
            role="button"
            className={
              'navbar-burger burger' + (isNavExpanded ? ' is-active' : '')
            }
            aria-label="menu"
            aria-expanded={isNavExpanded}
            tabIndex={0}
            data-target="navbarMain"
            onClick={() => setNavExpanded(!isNavExpanded)}
            onKeyPress={() => setNavExpanded(!isNavExpanded)}
          >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div
          id="navbarMain"
          className={'navbar-menu' + (isNavExpanded ? ' is-active' : '')}
        >
          <div className="navbar-start">
            {(THEME.tabs || []).map((t) => (
              <Link key={t.id} href={`/tab/${t.id}`}>
                <a>{t.name}</a>
              </Link>
            ))}
          </div>

          <div className="navbar-end">
            {THEME.social && !isTablet ? (
              <PageSocial className={tw['mobile:w-full']} />
            ) : null}

            <form
              className="field has-addons m-2 px-2"
              onSubmit={(ev) => {
                if (router.pathname.startsWith('/post/')) {
                  ev.preventDefault()
                  router.push(`/blog?q=${encodeURIComponent(q)}`)
                }
              }}
            >
              <div className="control is-expanded" role="search">
                <input
                  value={q}
                  onInput={(ev) => setQ((ev.target as HTMLInputElement).value)}
                  className="input"
                  type="search"
                  placeholder="Search"
                  aria-label="search"
                />
              </div>

              <div className="control">
                <button
                  className="button"
                  style={{
                    borderTopRightRadius: '100%',
                    borderBottomRightRadius: '100%'
                  }}
                >
                  <span className="icon">
                    <FontAwesomeIcon icon={faSearch} />
                  </span>
                </button>
              </div>
            </form>
          </div>
        </div>
      </nav>

      <article style={{ marginTop: '60px' }}>
        <div className="container">
          <div className="columns">
            <main
              className={
                'column mt-4' + THEME.sidebar
                  ? 'is-6-desktop is-offset-1-desktop'
                  : 'is-8-desktop is-offset-2-desktop'
              }
            >
              {children}
            </main>

            {THEME.sidebar ? (
              <aside className="column is-4">
                {THEME.sidebar.tagCloud ? (
                  <section className="card mt-4">
                    <header className="card-header">
                      <h3 className="card-header-title">Tag Cloud</h3>
                    </header>

                    <article className="card-content">
                      {computedTags.map((t) => (
                        <span key={t.name} className="el-tag mr-2">
                          <Link href={`/tag/${t.name}`}>
                            <a className={t.class}>{t.name}</a>
                          </Link>
                        </span>
                      ))}
                    </article>
                  </section>
                ) : null}

                {THEME.sidebar.twitter ? (
                  <section className="card mt-4">
                    <a
                      ref={twitterRef}
                      className="twitter-timeline"
                      data-height="800"
                      href={`https://twitter.com/${THEME.sidebar.twitter}`}
                    >
                      Tweets by {THEME.sidebar.twitter}
                    </a>
                  </section>
                ) : null}
              </aside>
            ) : null}
          </div>
        </div>
      </article>
    </section>
  )
}

export default Layout
