// packages/nuxt/components/PageSocial.vue
<template>
  <div
    :class="
      [
        $style['inline-flex'],
        $style['justify-center'],
        $style['self-center'],
      ].join(' ')
    "
  >
    <a
      v-if="social.facebook"
      class="navbar-item"
      :href="`https://facebook.com/${social.facebook}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'facebook-f']" />
      </span>
    </a>

    <a
      v-if="social.twitter"
      class="navbar-item"
      :href="`https://twitter.com/${social.twitter}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'twitter']" />
      </span>
    </a>

    <a
      v-if="social.reddit"
      class="navbar-item"
      :href="`https://www.reddit.com/user/${social.reddit}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'reddit']" />
      </span>
    </a>

    <a
      v-if="social.quora"
      class="navbar-item"
      :href="`https://www.quora.com/profile/${social.quora}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'quora']" />
      </span>
    </a>

    <a
      v-if="social.linkedin"
      class="navbar-item"
      :href="`https://www.linkedin.com/in/${social.linkedin}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'linkedin-in']" />
      </span>
    </a>

    <a
      v-if="social.github"
      class="navbar-item"
      :href="`https://github.com/${social.github}`"
      target="_blank"
      rel="noopener nofollow noreferrer"
    >
      <span class="icon">
        <FontAwesome :icon="['fab', 'github']" />
      </span>
    </a>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component
export default class PageSocial extends Vue {
  social = JSON.parse(process.env.social!)
}
</script>

<style module scoped src="~/styles/tw.module.css"></style>

// packages/next/components/PageSocial.tsx
import {
  faGithub,
  faQuora,
  faReddit,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import tw from "~/styles/tw.module.css";

const PageSocial = () => {
  const social = JSON.parse(process.env.social!);

  return (
    <div
      className={[
        tw["inline-flex"],
        tw["justify-center"],
        tw["self-center"],
      ].join(" ")}
    >
      {social.twitter ? (
        <a
          className="navbar-item"
          href={`https://twitter.com/${social.twitter}`}
          target="_blank"
          rel="noopener nofollow noreferrer"
        >
          <span className="icon">
            <FontAwesomeIcon icon={faTwitter} />
          </span>
        </a>
      ) : null}

      {social.reddit ? (
        <a
          className="navbar-item"
          href={`https://www.reddit.com/user/${social.reddit}`}
          target="_blank"
          rel="noopener nofollow noreferrer"
        >
          <span className="icon">
            <FontAwesomeIcon icon={faReddit} />
          </span>
        </a>
      ) : null}

      {social.quora ? (
        <a
          className="navbar-item"
          href={`https://www.quora.com/profile/${social.quora}`}
          target="_blank"
          rel="noopener nofollow noreferrer"
        >
          <span className="icon">
            <FontAwesomeIcon icon={faQuora} />
          </span>
        </a>
      ) : null}

      {social.github ? (
        <a
          className="navbar-item"
          href={`https://github.com/${social.github}`}
          target="_blank"
          rel="noopener nofollow noreferrer"
        >
          <span className="icon">
            <FontAwesomeIcon icon={faGithub} />
          </span>
        </a>
      ) : null}
    </div>
  );
};

export default PageSocial;
