// packages/web/components/Pagination.vue
<template>
  <section class="my-4 mx-2">
    <nav
      class="pagination is-rounded"
      role="navigation"
      aria-label="pagination"
    >
      <nuxt-link
        v-if="page > 1"
        :to="setPageUrl(page - 1)"
        class="pagination-previous"
      >
        <span class="icon">
          <FontAwesome icon="caret-left" />
        </span>

        <span :class="$style['sr-only']"> Previous </span>
      </nuxt-link>

      <nuxt-link
        v-if="page < total - 1"
        :to="setPageUrl(page + 1)"
        class="pagination-next"
      >
        <span class="icon">
          <FontAwesome icon="caret-right" />
        </span>

        <span :class="$style['sr-only']"> Next </span>
      </nuxt-link>

      <ul class="pagination-list">
        <li v-if="page > 1">
          <nuxt-link
            :to="setPageUrl(1)"
            class="pagination-link"
            aria-label="go to page 1"
          >
            1
          </nuxt-link>
        </li>

        <li v-if="page > 3">
          <span class="pagination-ellipsis"> &hellip; </span>
        </li>

        <li v-if="page > 2">
          <nuxt-link
            :to="setPageUrl(page - 1)"
            class="pagination-link"
            :aria-label="`go to page ${page - 1}`"
          >
            {{ page - 1 }}
          </nuxt-link>
        </li>

        <li>
          <nuxt-link
            :to="setPageUrl(page)"
            class="pagination-link is-current"
            :aria-label="`go to page ${page}`"
            aria-current="page"
          >
            {{ page }}
          </nuxt-link>
        </li>

        <li v-if="page < total - 1">
          <nuxt-link
            :to="setPageUrl(page + 1)"
            class="pagination-link"
            :aria-label="`go to page ${page + 1}`"
          >
            {{ page + 1 }}
          </nuxt-link>
        </li>

        <li v-if="page < total - 2">
          <span class="pagination-ellipsis">&hellip;</span>
        </li>

        <li v-if="page < total">
          <nuxt-link
            :to="setPageUrl(total)"
            class="pagination-link"
            :aria-label="`go to page ${total}`"
          >
            {{ total }}
          </nuxt-link>
        </li>
      </ul>
    </nav>
  </section>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'

@Component
export default class Pagination extends Vue {
  @Prop({ required: true }) total!: string

  get page() {
    return parseInt((this.$route.path.match(/\/(\d+)?$/) || [])[1] || '1')
  }

  setPageUrl(p: number) {
    const {
      path,
      query: { q },
    } = this.$route
    const path0 = path.replace(/\/(\d+)?$/, '')

    return this.$router.resolve({
      path: `${path0 || '/blog'}${p === 1 ? '' : `/${p}`}`,
      query: { q },
    }).href
  }
}
</script>

<style module scoped src="~/styles/tw.module.css"></style>

// packages/next/components/Pagination.tsx
import { faCaretLeft, faCaretRight } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import tw from "~/styles/tw.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const Pagination = ({ total }: { total: number }) => {
  const router = useRouter();
  const page = parseInt((router.pathname.match(/\/(\d+)?$/) || [])[1] || "1");

  const setPageUrl = (p: number) => {
    const {
      pathname,
      query: { q },
    } = router;
    const path0 = pathname.replace(/\/(\d+)?$/, "");

    return `${path0 || "/blog"}${p === 1 ? "" : `/${p}`}${
      q ? `?q=${encodeURIComponent(q as string)}` : ""
    }`;
  };

  return (
    <section className="my-4 mx-2">
      <nav
        className="pagination is-rounded"
        role="navigation"
        aria-label="pagination"
      >
        {page > 1 ? (
          <Link href={setPageUrl(page - 1)}>
            <a className="pagination-previous">
              <span className="icon">
                <FontAwesomeIcon icon={faCaretLeft} />
              </span>

              <span className={tw["sr-only"]}>Previous</span>
            </a>
          </Link>
        ) : null}

        {page < total - 1 ? (
          <Link href={setPageUrl(page + 1)}>
            <a className="pagination-next">
              <span className="icon">
                <FontAwesomeIcon icon={faCaretRight} />
              </span>

              <span className={tw["sr-only"]}>Next</span>
            </a>
          </Link>
        ) : null}

        <ul className="pagination-list">
          {page > 1 ? (
            <Link href={setPageUrl(1)}>
              <a className="pagination-link" aria-label="go to page 1">
                1
              </a>
            </Link>
          ) : null}

          {page > 3 ? (
            <li>
              <span className="pagination-ellipsis">&hellip;</span>
            </li>
          ) : null}

          {page > 2 ? (
            <Link href={setPageUrl(page - 1)}>
              <a
                className="pagination-link"
                aria-label={`go to page ${page - 1}`}
              >
                {page - 1}
              </a>
            </Link>
          ) : null}

          <li>
            <Link href={setPageUrl(page)}>
              <a
                className="pagination-link is-current"
                aria-label={`go to page ${page}`}
                aria-current="page"
              >
                {page}
              </a>
            </Link>
          </li>

          {page < total - 1 ? (
            <li>
              <Link href={setPageUrl(page + 1)}>
                <a
                  className="pagination-link"
                  aria-label={`go to page ${page + 1}`}
                >
                  {page + 1}
                </a>
              </Link>
            </li>
          ) : null}

          {page < total - 2 ? (
            <li>
              <span className="pagination-ellipsis">&hellip;</span>
            </li>
          ) : null}

          {page < total ? (
            <Link href={setPageUrl(total)}>
              <a className="pagination-link" aria-label={`go to page ${total}`}>
                {total}
              </a>
            </Link>
          ) : null}
        </ul>
      </nav>
    </section>
  );
};

export default Pagination;
