// packages/web/components/PostFull.vue
<template>
  <section>
    <article class="card mb-4">
      <div class="card-content">
        <PostHeader :post="post" />

        <div v-if="post.image" class="mx-6 mb-4">
          <img class="tw-w-full" :src="post.image" :alt="post.title" />
        </div>

        <h1 class="title">{{ post.title }}</h1>

        <div class="content" v-html="post.contentHtml" />

        <div style="overflow-wrap: break-word">
          <span class="tw-mr-2">Tags:</span>
          <nuxt-link
            v-for="t in post.tag || []"
            :key="t"
            :to="`/tag/${t}`"
            class="mr-2"
            >{{ t }}</nuxt-link
          >
        </div>
      </div>
    </article>

    <footer v-if="hasComment" class="card my-4">
      <div class="card-content">
        <div ref="remark42" />
      </div>
    </footer>
  </section>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from 'nuxt-property-decorator'

import '~/assets/remark42'

import PostHeader from './PostHeader.vue'

@Component({
  components: {
    PostHeader,
  },
})
export default class PostFull extends Vue {
  @Prop({ required: true }) post!: any

  hasComment = !!process.env.remark42Config
  remark42Instance: any = null

  get pageUrl() {
    return process.env.baseUrl + this.$route.path
  }

  mounted() {
    if (window.REMARK42) {
      this.initRemark42()
    } else {
      window.addEventListener('REMARK42::ready', () => {
        this.initRemark42()
      })
    }
  }

  beforeDestroy() {
    if (this.remark42Instance) {
      this.remark42Instance.destroy()
    }
  }

  beforeRouteLeave() {
    if (this.remark42Instance) {
      this.remark42Instance.destroy()
    }
  }

  @Watch('$route.path')
  onRouteChange() {
    this.initRemark42()
  }

  initRemark42() {
    if (process.client && process.env.remark42Config && window.REMARK42) {
      if (this.remark42Instance) {
        this.remark42Instance.destroy()
      }

      const config = JSON.parse(process.env.remark42Config)

      this.remark42Instance = window.REMARK42.createInstance({
        node: this.$refs.remark42 as HTMLElement,
        host: config.host,
        site_id: config.siteId,
      })
    }
  }
}
</script>

// packages/next/components/PostFull.tsx
import "~/assets/remark42";

import Link from "next/link";
import { useRouter } from "next/router";
import { createRef, useEffect } from "react";

import PostHeader from "./PostHeader";

let remark42Instance: any = null;

const router = useRouter();

router.beforePopState(() => {
  if (remark42Instance) {
    remark42Instance.destroy();
  }
  return true;
});

const PostFull = (post: any) => {
  const remark42 = createRef<HTMLDivElement>();

  useEffect(() => {
    const initRemark42 = () => {
      if (process.env.remark42Config && window.REMARK42) {
        if (remark42Instance) {
          remark42Instance.destroy();
        }

        const config = JSON.parse(process.env.remark42Config);

        remark42Instance = window.REMARK42.createInstance({
          node: remark42.current,
          host: config.host,
          site_id: config.siteId,
        });
      }
    };

    if (window.REMARK42) {
      initRemark42();
    } else {
      window.addEventListener("REMARK42::ready", () => {
        initRemark42();
      });
    }
  });

  return (
    <section>
      <article className="card mb-4">
        <div className="card-content">
          <PostHeader {...{ post }} />

          <div v-if="post.image" className="mx-6 mb-4">
            <img
              className="tw-w-full"
              src={post.image}
              alt={post.title}
              style={{ width: "100%" }}
            />
          </div>

          <h1 className="title">{post.title}</h1>

          <div
            className="content"
            dangerouslySetInnerHTML={{ __html: post.contentHtml }}
          />

          <div style={{ overflowWrap: "break-word" }}>
            <span className="mr-2">Tags:</span>
            {(post.tag || []).map((t: string) => {
              return (
                <Link key={t} href={`/tag/${t}`}>
                  <a className="mr-2">{t}</a>
                </Link>
              );
            })}
          </div>
        </div>
      </article>

      <footer v-if="hasComment" className="card my-4">
        <div className="card-content">
          <div ref={remark42} />
        </div>
      </footer>
    </section>
  );
};

export default PostFull;
